=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kiqr::CoreApi::SchemasApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SchemasApi' do
  before do
    # run before each test
    @api_instance = Kiqr::CoreApi::SchemasApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SchemasApi' do
    it 'should create an instance of SchemasApi' do
      expect(@api_instance).to be_instance_of(Kiqr::CoreApi::SchemasApi)
    end
  end

  # unit tests for create_schema
  # Create a schema
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project_id 
  # @option opts [CreateSchemaRequest] :create_schema_request 
  # @return [Schema]
  describe 'create_schema test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_schema
  # Retrieve details about schema
  # @param schema_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project_id 
  # @return [Schema]
  describe 'get_schema test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_schemas
  # Retrieve a projects history of schemas
  # @param [Hash] opts the optional parameters
  # @option opts [String] :project_id 
  # @return [Array<Schema>]
  describe 'get_schemas test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
