=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.5.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kiqr::CoreApi::SessionApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SessionApi' do
  before do
    # run before each test
    @api_instance = Kiqr::CoreApi::SessionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SessionApi' do
    it 'should create an instance of SessionApi' do
      expect(@api_instance).to be_instance_of(Kiqr::CoreApi::SessionApi)
    end
  end

  # unit tests for get_session_info
  # Returns current user, project and environment.
  # @param [Hash] opts the optional parameters
  # @return [SessionInfoResponse]
  describe 'get_session_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
