=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Kiqr::CoreApi::UserApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserApi' do
  before do
    # run before each test
    @api_instance = Kiqr::CoreApi::UserApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserApi' do
    it 'should create an instance of UserApi' do
      expect(@api_instance).to be_instance_of(Kiqr::CoreApi::UserApi)
    end
  end

  # unit tests for get_userinfo
  # Retrieve info about the current user
  # @param [Hash] opts the optional parameters
  # @return [User]
  describe 'get_userinfo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
