=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.9.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kiqr::CoreApi::ContentType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kiqr::CoreApi::ContentType do
  let(:instance) { Kiqr::CoreApi::ContentType.new }

  describe 'test an instance of ContentType' do
    it 'should create an instance of ContentType' do
      expect(instance).to be_instance_of(Kiqr::CoreApi::ContentType)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "fields"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
