=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.8.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kiqr::CoreApi::CreateSchemaRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kiqr::CoreApi::CreateSchemaRequest do
  let(:instance) { Kiqr::CoreApi::CreateSchemaRequest.new }

  describe 'test an instance of CreateSchemaRequest' do
    it 'should create an instance of CreateSchemaRequest' do
      expect(instance).to be_instance_of(Kiqr::CoreApi::CreateSchemaRequest)
    end
  end
  describe 'test attribute "commit_message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "content_types_raw"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
