=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.16.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kiqr::CoreApi::ProjectsCollectionMeta
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kiqr::CoreApi::ProjectsCollectionMeta do
  let(:instance) { Kiqr::CoreApi::ProjectsCollectionMeta.new }

  describe 'test an instance of ProjectsCollectionMeta' do
    it 'should create an instance of ProjectsCollectionMeta' do
      expect(instance).to be_instance_of(Kiqr::CoreApi::ProjectsCollectionMeta)
    end
  end
  describe 'test attribute "pagination"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
