=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.5.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Kiqr::CoreApi::SessionInfoResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Kiqr::CoreApi::SessionInfoResponse do
  let(:instance) { Kiqr::CoreApi::SessionInfoResponse.new }

  describe 'test an instance of SessionInfoResponse' do
    it 'should create an instance of SessionInfoResponse' do
      expect(instance).to be_instance_of(Kiqr::CoreApi::SessionInfoResponse)
    end
  end
  describe 'test attribute "environment"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "project"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "user"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
