=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.16.4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

module Kiqr::CoreApi
  VERSION = '1.0.0'
end
