=begin
#Core API

#Core API for KIQR Headless CMS

The version of the OpenAPI document: 0.13.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

module Kiqr::CoreApi
  VERSION = '1.0.0'
end
